from typing import Dict, List, Literal

## Types
ProfileType = Literal[
    "startup",
    "investors",
    "aspirants_individuals",
    "government",
    "mentor_sme",
    "incubation_acceleration",
    "industry_corporate",
    "ecosystem_service_provider",
    "others",
]

## Constants
SECTOR_VALUES = [
    "sector_agnostic",
    "aerospace_defence_spacetech",
    "agriculture_foodtech",
    "ai_ml_iot",
    "art_culture_architecture",
    "automotive_ev_smart_mobility",
    "blue_economy",
    "chemicals_materials",
    "circular_economy",
    "climate_tech_clean_energy",
    "data_mining_analytics",
    "edutech",
    "femtech",
    "fintech_insurtech",
    "healthcare_life_sciences",
    "hr_tech_smart_workforce",
    "industry_4_advanced_manufacturing",
    "lifestyle_personalcare_d2c",
    "marketing_tech_mice",
    "media_entertainment",
    "proptech_legaltech_regtech",
    "retail_tech",
    "saas_software_it_ites",
    "smart_cities_e_governance",
    "social_impact_rural_livelihood_sustainability",
    "sports_tech_gaming",
    "supply_chain_logistics",
    "telecom_networking_hardware",
    "textiletech_fashion",
    "travel_tourism",
    "web3_blockchain_vr_ar",
]

PROFILE_VALUES = [
    "startup",
    "investors",
    "aspirants_individuals",
    "government",
    "mentor_sme",
    "incubation_acceleration",
    "industry_corporate",
    "ecosystem_service_provider",
    "others",
]

PROFILE_SUBTYPE: Dict[ProfileType, List[str]] = {
    "startup": ["DPIIT", "Non DPIIT"],
    "aspirants_individuals": ["College Students", "Working Professionals"],
    "incubation_acceleration": ["Incubators", "Accelerators"],
    "government": ["State Government", "Union Government", "International"],
    "investors": [
        "Banks",
        "HNIs",
        "Angel Investor",
        "Venture Capitalists (VCs)",
        "Angel Networks",
        "Family Office",
        "Private Equity",
        "Revenue Based Financing",
        "Venture Debt",
        "Limited Partners",
    ],
    "mentor_sme": ["Mentor", "Subject Matter Expert"],
    "ecosystem_service_provider": [
        "Education Institution",
        "Business & Social Forums",
        "Startup Community",
        "NGO",
        "Media Agency",
        "R&D Agency",
        "Legal & Compliance Services",
        "Consulting and Advisory Services",
        "Coworking Space",
        "Makerspace",
        "Financial Services",
        "Technology Services",
        "Marketing and Branding Services",
        "Design Agency",
        "Industry Association",
    ],
    "industry_corporate": [""],
    "others": [""],
}

DESIGNATIONS_LABELS = {
    "startup": [
        "CEO",
        "Founder / Co-founder",
        "COO (Chief Operating Officer)",
        "CTO (Chief Technology Officer)",
        "CMO (Chief Marketing Officer)",
        "CFO (Chief Financial Officer)",
        "Head of Product / Product Manager",
        "Head of Operations",
        "Head of Business Development / Partnerships",
        "Head of Marketing & Sales",
        "Innovation Lead / R&D Lead",
        "Community / Growth Manager",
        "Technology Head",
        "Others",
    ],
    "others": ["Others"],
    "ecosystem_service_provider": [
        "CEO",
        "Founder",
        "Country Head / Regional Head",
        "Program Director",
        "Community / Ecosystem Manager",
        "Partnerships & Alliances Head",
        "Legal / Compliance Advisor",
        "Technology Partner Lead",
        "Media / PR Partner Head",
        "CSR / NGO Head",
        "Others",
    ],
    "incubation_acceleration": [
        "CEO",
        "Director",
        "Head of Incubator",
        "Program Head / Program Manager",
        "Startup Portfolio Manager",
        "Community Manager",
        "Partnerships Manager",
        "Technical Mentor / Entrepreneur-in-Residence (EIR)",
        "Innovation Manager",
        "Investment Manager / Seed Fund Manager",
        "Academic Researcher",
        "Business Development Professional",
        "Legal Professional",
        "Finance Professional",
        "Marketing / Branding Professional",
        "Designer",
        "Others",
    ],
    "mentor_sme": [
        "Serial Entrepreneur",
        "Angel Investor / Venture Partner (Mentor)",
        "Industry Expert / Domain Specialist",
        "Professor / Academic Expert",
        "Executive Coach / Leadership Coach",
        "Domain Expert (Tech / Marketing / Finance / Legal / IP / HR)",
        "Retired Senior Executive (CXO-level)",
        "Startup Advisor / Board Member",
        "Others",
    ],
    "government": [
        "Collector",
        "Secretary / Additional Secretary (Industries, IT, MSME, Skill, etc.)",
        "Director (Startup / Innovation Mission / MSME / R&D)",
        "Mission Director / Program Director",
        "Joint Secretary / Deputy Secretary",
        "District Industries Centre (DIC) Head",
        "Nodal Officer (Innovation / Entrepreneurship / Trade)",
        "Trade Commissioner / Consulate Representative (International)",
        "Policy Advisor / Consultant",
        "Others",
    ],
    "industry_corporate": [
        "Chairman / Managing Director",
        "CEO",
        "COO",
        "CTO",
        "CFO",
        "Chief Innovation Officer / Head of Innovation",
        "Corporate Strategy Head",
        "Business Unit Head",
        "Head of Open Innovation / Startup Partnerships",
        "CSR / ESG Head",
        "R&D Director",
        "Procurement / Supply Chain Head",
        "Digital Transformation Head",
        "Others",
    ],
    "investors": [
        "Angel Investor",
        "Managing Partner / General Partner (VC/ PE)",
        "Principal",
        "Fund Manager / Portfolio Manager",
        "Analyst / Associate (VC, PE, Bank)",
        "Relationship Manager (Banking / HNI)",
        "Family Office Head / Wealth Manager",
        "Others",
    ],
    "aspirants_individuals": [
        "Student (UG / PG / Research Scholar / PhD)",
        "Recent Graduate",
        "Working Professional (Engineer / Manager / Consultant)",
        "Startup Enthusiast / Early-Stage Founder",
        "Researcher / Innovator",
        "Freelancer / Independent Consultant",
        "Aspiring Entrepreneur",
        "Others",
    ],
}

BUSINESS_TYPE = ["Product based", "Service based", "Product & Service based"]

SERVICE_TYPE_LABELS: Dict[ProfileType, List[str]] = {
    "startup": BUSINESS_TYPE,
    "aspirants_individuals": [""],
    "industry_corporate": BUSINESS_TYPE,
    "mentor_sme": [""],
    "government": BUSINESS_TYPE,
    "investors": BUSINESS_TYPE,
    "ecosystem_service_provider": BUSINESS_TYPE,
    "others": BUSINESS_TYPE,
    "incubation_acceleration": [""],
}

OFFERINGS: Dict[ProfileType, List[str]] = {
    "startup": [
        "Offer product or services at subsidized rates to peer Startups",
        "Provide mentorship and advisory support to budding founders",
        "Would love to offer access to workspace, labs, or infrastructure to budding founders",
        "Would love to facilitate introductions to investors and funding networks",
        "Would love to connect peers to potential clients or business partners",
        "Would love opportunity to collaborate with startups for pilots, partnerships, or joint projects",
        "Others",
    ],
    "industry_corporate": [
        "Provide pilot projects and proof-of-concept opportunities",
        "Offer corporate partnerships and procurement channels",
        "Share infrastructure, labs, and testing facilities",
        "Provide mentorship and domain expertise",
        "Facilitate access to supply chain and distribution networks",
        "Invest in startups through corporate venture arms (CVCs)",
        "Enable global market access and cross-border partnerships",
        "Others",
    ],
    "mentor_sme": [""],
    "ecosystem_service_provider": [
        "Provide research, innovation, and IP support",
        "Offer training, workshops, and skilling programs",
        "Facilitate access to students and talent pipelines",
        "Provide legal, financial, and compliance services",
        "Offer discounted consulting, tech, or design services",
        "Enable networking through forums, associations, and media",
        "Provide co-working and maker spaces for startups",
        "Support startups with CSR and NGO-led initiatives",
        "Create visibility through media and outreach platforms",
        "Facilitate global collaborations and partnerships",
        "Others",
    ],
    "others": [""],
    "government": [
        "Provide grants, subsidies, and seed funding programs",
        "Offer incubation and acceleration support through government-led hubs",
        "Enable policy support and ease of doing business initiatives",
        "Facilitate market access via trade delegations and events",
        "Provide infrastructure and co-working spaces at concessional rates",
        "Create awareness through startup campaigns and outreach",
        "Connect startups to national and international programs",
        "Others",
    ],
    "incubation_acceleration": [
        "Provide structured incubation and acceleration programs",
        "Offer seed funding or stipends for selected startups",
        "Facilitate mentorship and expert sessions",
        "Provide access to investors and funding opportunities",
        "Offer workspace, labs, and shared infrastructure",
        "Support with compliance, IP, and legal assistance",
        "Offer opportunities like demo days, pitch sessions, and networking events",
        "Others",
    ],
    "investors": [
        "Provide seed, early-stage, and growth funding",
        "Offer mentorship and strategic guidance to startups",
        "Facilitate co-investment and syndicate opportunities",
        "Connect startups to portfolio companies for partnerships",
        "Share industry insights and market intelligence",
        "Support with scaling and go-to-market strategies",
        "Enable access to global investor networks",
        "Others",
    ],
    "aspirants_individuals": [""],
}

STARTUP_STAGES = [
    "Ideation",
    "Validation",
    "MVP",
    "Seed Stage",
    "Early Traction",
    "Growth Stage",
]

STARTUP_FUNDS = [
    "Bootstrapped",
    "< INR 10 Lakh",
    "INR 10 Lakh - INR 50 Lakh",
    "INR 50 Lakh - INR 1 Cr",
    "INR 1 Cr - INR 10 Cr",
    "> INR 10 Cr",
]


STARTUP_REVENUE = [
    "Pre-revenue",
    "< INR 10 Lakh",
    "INR 10 Lakh - INR 50 Lakh",
    "INR 50 Lakh - INR 1 Cr",
    "INR 1 Cr - INR 10 Cr",
    "> INR 10 Cr",
]

BUSINESS_MODEL = ["B2B", "B2B2C", "B2C", "B2G", "D2C"]

## Investors
TICKET_SIZE = [
    "5 Lakhs to 15 Lakhs",
    "15 Lakhs to 1 Crore",
    "1 Crore to 5 Crore",
    "More than 5 Crore",
]

INVESTMENT_INSTRUMENTS = ["Convertible Notes", "Debt", "Equity", "Open to all"]


##

LOOKING_FOR: Dict[ProfileType, List[str]] = {
    "startup": [
        "Funding",
        "Mentorship",
        "Market Access (Domestic)",
        "Market Access (International / Global Expansion)",
        "Corporate Partnerships",
        "Government Procurement",
        "Incubation / Acceleration Programs",
        "Hiring Support",
        "Product Development / R&D Support",
        "Technology / Infrastructure Credits",
        "Legal, Compliance & IP Support",
        "Manufacturing / Bulk Production Support",
        "Certifications & Licensing Support",
        "Import / Export & International Trade Support",
        "Marketing, Branding & PR",
        "Media Visibility",
        "Networking & Community",
        "Others",
    ],
    "industry_corporate": [
        "Access to Innovative Startups & Technologies",
        "Startup Pilots & Proof of Concept Opportunities",
        "Corporate Venture Investment Opportunities",
        "Collaboration with Incubators & Accelerators",
        "Co-development of Products & Solutions",
        "Access to Skilled Startup Talent & Interns",
        "CSR & Social Impact Partnership Opportunities",
        "Market Expansion & Global Collaboration",
        "Others",
    ],
    "ecosystem_service_provider": [
        "Access to Startups & Innovators",
        "Industry & Government Collaborations",
        "Visibility & Branding in Ecosystem Events",
        "Opportunities to Deliver Services",
        "Partnerships for Research & Development",
        "CSR & Social Impact Partnerships",
        "Networking & Knowledge Sharing Platforms",
        "International Collaboration Opportunities",
        "Others",
    ],
    "mentor_sme": [
        "Access to High-Potential Startups for Mentorship",
        "Opportunities to Guide Startups in Growth, Strategy & Fundraising",
        "Networking with Investors, Founders & Corporates",
        "Academic & Research Collaboration Opportunities",
        "Others",
    ],
    "others": [
        "Access to High-Potential Startups for Mentorship",
        "Opportunities to Guide Startups in Growth, Strategy & Fundraising",
        "Networking with Investors, Founders & Corporates",
        "Academic & Research Collaboration Opportunities",
        "Others",
    ],
    "government": [
        "Connect with Startups for Schemes / Grants",
        "Industry & Corporate Partnerships",
        "International Collaboration Opportunities",
        "Policy Feedback from Startups / Investors",
        "Universities & R&D Linkages",
        "Participation in Global Trade & Delegations",
        "Innovation for Public Sector Challenges",
        "Others",
    ],
    "incubation_acceleration": [
        "High-Potential Startup Applications",
        "Access to Funding & Investor Networks",
        "Corporate Partners for Startup Pilots",
        "Government Support & Recognition Programs",
        "Academic / R&D Collaborations",
        "Access to Mentors & Industry Experts",
        "International Exchange & Delegations",
        "Opportunities for Global Partnerships",
        "Others",
    ],
    "investors": [
        "Startup Deal Flow",
        "Co-investment & Syndication Opportunities",
        "Access to Government Fund of Funds",
        "Potential Limited Partners (LPs)",
        "Fundraising Support for Investor’s Fund",
        "Corporate Partnerships for Portfolio Startups",
        "Market Access Support for Portfolio Companies",
        "Exit Opportunities (M&A, IPO)",
        "Access to Ecosystem Events & Demo Days",
        "Pipeline from Incubators & Accelerators",
        "Others",
    ],
    "aspirants_individuals": [
        "Mentorship & Guidance",
        "Internships",
        "Job Opportunities in Startups",
        "Entrepreneurship Skill Development Programs",
        "Access to Startup Events & Networking",
        "Co-founders / Teaming Opportunities",
        "Research / Innovation Projects",
        "Access to Pre Incubation program",
        "Others",
    ],
}
